export const GameRules = {
    CHOOSE_TILE_DURATION: 6,
    REVEAL_TILE_DURATION: 8,
    FACE_OFF_DURATION: 20,
    GAME_BEGIN_DURATION: 5,
    PLAYER_DEF_DURATION: 5,

    DEFAULT_MAX_MOVE_IN_TURN: 1,
    PLAYER_MOVING_DURATION: 2,
    MAX_PLAYER_IN_ROOM: 2,

    NUMBER_OF_EMPTY_TILE: 3,

}